### ISSUE TITLE
New template to check encoding on CI

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.usethis#36]
@cjyetman recently developed a new gh-workflow to
check for correct encodings. It would be nice to
add it in inst/templates/check_encodings.yml so 
we can easily reuse it with 

    use_template("check_encodings.yml", package = "r2dii.usethis")

cc @jdhoffa

**Comment by cjyetman** [comment]
for reference, the latest version is here: https://github.com/2DegreesInvesting/.github/blob/master/.github/workflow-templates/pr-file-encodings.yml
